apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api-gateway
  template:
    metadata:
      labels:
        app: k8s-api-gateway
    spec:
      containers:
        - name: k8s-api-gateway
          image: wkdnffla3/k8s-api-gateway:0.0.5
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: api-gateway-config-volume
            - name : api-gateway-secret-volume
              mountPath: /etc/secret
      volumes:
        - name: api-gateway-config-volume
          configMap:
            name: api-gateway-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: api-gateway-secret-volume
          secret:
            secretName: api-gateway-secret
            items:
              - key: application-secret.yml
                path: application-secret.yml